var cards = '{"card":"Expressa um agradecimento por algo que tenhas vivido com alguém deste grupo","url":"images/agradecimento.png" },'
 +' {"card":"Qual foi a coisa mais louca que fizeste na vida?","url":"images/coisamaislouca.png"},'
 +' {"card":"Como farias para adormecer um bébé?","url":"images/comoadormecesbebe.png"},'
 +' {"card":"Conta ao grupo por gestos como aprendeste a andar de bicicleta","url":"images/comoaprendestebicicleta.png"},'
 +' {"card":"Conta ao grupo como chegaste aqui hoje. Depois pede ao grupo para contar esta história contigo","url":"images/comochegasteaquihoje.png"},'
 +' {"card":"Como nasceste?","url":"images/comonasceste.png"},'
 +' {"card":"Como é que foi o teu brimeiro beijo?","url":"images/comoprimeirobeijo.png"},'
 +' {"card":"Como te estás a sentir neste momento?","url":"images/comotesentes.png"},'
 +' {"card":"Convida alguém do grupo para cantar contigo uma canção de que gostes. Podem improvisar instrumentos.","url":"images/convidacantarcontigo.png"},'
 +' {"card":"Representa com o teu corpo uma situação em que te sentes bloqueado na tua vida atual","url":"images/corposituacaobloqueado.png"},'
 +' {"card":"Inventa uma dança com sons. Podes envolver mais pessoas do grupo","url":"images/dancacomsons.png"},'
 +' {"card":"Faz uma dança em que moves 3 partes do corpo em simultâneo","url":"images/dancatrespartescorpo.png"},'
 +' {"card":"Imita um animal de que gostes sem revelar qual é","url":"images/imitaanimal.png"},'
 +' {"card":"Faz uma massagem nos ombros da pessoa que está À tua direita","url":"images/massagemadireita.png"},'
 +' {"card":"Convida todo o grupo a fazer uma massagem coletiva.","url":"images/massagemcoletiva.png"},'
 +' {"card":"Qual foi o momento mais alegre que viveste nos últimos sete dias?","url":"images/momentomaisalegre.png"},'
 +' {"card":"Qual foi o momento mais desafiante que viveste nos últimos cinco anos?","url":"images/momentomaisdesafiante.png"},'
 +' {"card":"Qual foi o momento mais divertido que viveste no último ano?","url":"images/momentomaisdivertidoano.png"},'
 +' {"card":"Qual foi o momento mais divertido que viveste na última semana?","url":"images/momentomaisdivertidosemana.png"},'
 +' {"card":"Qual foi o momento + triste que viveste nos últimos 3 meses?","url":"images/momentomaistriste.png"},'
 +' {"card":"Mostra ao grupo o que guardas na tua carteira.","url":"images/oqueguardascarteira.png"},'
 +' {"card":" Blank Card ","url":"images/Surprise.png"},'
 +' {"card":"O que é que te faz corar?","url":"images/oquetefazcorar.png"},'
 +' {"card":"O que perguntarias a Deus?","url":"images/perguntaadeus.png"},'
 +' {"card":"Qual é a pergunta que gostavas que te fizessem?","url":"images/perguntatefizessem.png"},'
 +' {"card":"Qual é a primeira coisa que fazes ao acordar ?","url":"images/primeiracoisaacordar.png"},'
 +' {"card":" Blank Card ","url":"images/Surprise.png"},'
 +' {"card":"Que pergunta gostavas de fazer à pessoa que está à tua frente ? Porquê ? ","url":"images/queperguntapessoafrente.png"},'
 +' {"card":"Conta ao grupo algo que gostarias de realizar nos próximos 2 anos.","url":"images/realizarproximosdoisanos.png"},'
 +' {"card":"Se fosses um animal que animal gostavas de ser ? Porquê?","url":"images/sefossesanimal.png"},'
 +' {"card":"Se fosses um jornalista, quem gostarias de entrevistar? Porquê ?","url":"images/sefossesjornalista.png"},'
 +' {"card":"Se fosses um objeto deste lugar, qual serias? Porquê ?","url":"images/sefossesobjeto.png"},'
 +' {"card":"Se fosses uma planta, qual serias? Porquê ?","url":"images/sefossesplanta.png"},'
 +' {"card": "Encomende já o Papo a Papo enviando email para papoapapo2020@gmail.com","url":""},'
 +' {"card":"Conta uma situação marcante que viveste com uma pessoa deste grupo.","url":"images/situacaomarcante.png"},'
 +' {"card":"Tens a tua sobrevivência garantida. Em que te ocupas?","url":"images/sobrevivenciagarantida.png"},'
 +' {"card":"Quais são os teus três maiores valores ?","url":"images/tresmaioresvalores.png"},'
 +' {"card": "Alguma vez viste a tua vida andar pra trás?","url":"images/vidaandarparatras.png"},'
 +' {"card": "Se fosses um livro, que livro serias? Porquê?", "url":""},'
 +' {"card": "Encomende já o Papo a Papo enviando email para papoapapo2020@gmail.com","url":""}';