var cards = '{"card":"Expressa um agradecimento por algo que tenhas vivido com alguém deste grupo","url":"images/agradecimento.jpg" },'
 +' {"card":"Qual foi a coisa mais louca que fizeste na vida?","url":"images/coisamaislouca.jpg"},'
 +' {"card":"CCanta ao grupo uma música que usarias para adormecer um bébé. (sem os adormecer)","url":"images/musicaadormecerbebe.jpg"},'
 +' {"card":"Conta ao grupo por gestos como aprendeste a andar de bicicleta","url":"images/comoaprendestebicicleta.jpg"},'
 +' {"card":"Conta ao grupo como chegaste aqui hoje. Depois pede ao grupo para contar esta história contigo","url":"images/comochegasteaquihoje.jpg"},'
 +' {"card":"Como nasceste?","url":"images/comonasceste.jpg"},'
 +' {"card":"Como é que foi o teu brimeiro beijo?","url":"images/comoprimeirobeijo.jpg"},'
 +' {"card":"Como te estás a sentir neste momento?","url":"images/comotesentes.jpg"},'
 +' {"card":"Convida alguém do grupo para cantar contigo uma canção de que gostes. Podem improvisar instrumentos.","url":"images/convidacantarcontigo.jpg"},'
 +' {"card":"Representa com o teu corpo uma situação em que te sentes bloqueado na tua vida atual","url":"images/corposituacaobloqueado.jpg"},'
 +' {"card":"Inventa uma dança com sons. Podes envolver mais pessoas do grupo","url":"images/dancacomsons.jpg"},'
 +' {"card":"Faz uma dança em que moves 3 partes do corpo em simultâneo","url":"images/dancatrespartescorpo.jpg"},'
 +' {"card":"Imita um animal de que gostes sem revelar qual é","url":"images/imitaanimal.jpg"},'
 +' {"card":"Faz uma massagem nos ombros da pessoa que está À tua direita","url":"images/massagemadireita.jpg"},'
 +' {"card":"Convida todo o grupo a fazer uma massagem coletiva.","url":"images/massagemcoletiva.jpg"},'
 +' {"card":"Qual foi o momento mais alegre que viveste nos últimos sete dias?","url":"images/momentomaisalegre.jpg"},'
 +' {"card":"Qual foi o momento mais desafiante que viveste nos últimos cinco anos?","url":"images/momentomaisdesafiante.jpg"},'
 +' {"card":"Qual foi o momento mais divertido que viveste no último ano?","url":"images/momentomaisdivertidoano.jpg"},'
 +' {"card":"Qual foi o momento mais divertido que viveste na última semana?","url":"images/momentomaisdivertidosemana.jpg"},'
 +' {"card":"Qual foi o momento + triste que viveste nos últimos 3 meses?","url":"images/momentomaistriste.jpg"},'
 +' {"card":"Mostra ao grupo o que guardas na tua carteira.","url":"images/oqueguardascarteira.jpg"},'
 +' {"card":" Blank Card ","url":"images/Surprise.jpg"},'
 +' {"card":"O que é que te faz corar?","url":"images/oquetefazcorar.jpg"},'
 +' {"card":"O que perguntarias a Deus?","url":"images/perguntaadeus.jpg"},'
 +' {"card":"Qual é a pergunta que gostavas que te fizessem?","url":"images/perguntatefizessem.jpg"},'
 +' {"card":"Qual é a primeira coisa que fazes ao acordar ?","url":"images/primeiracoisaacordar.jpg"},'
 +' {"card":" Blank Card ","url":"images/Surprise.jpg"},'
 +' {"card":"Que pergunta gostavas de fazer à pessoa que está à tua frente ? Porquê ? ","url":"images/queperguntapessoafrente.jpg"},'
 +' {"card":"Conta ao grupo algo que gostarias de realizar nos próximos 2 anos.","url":"images/realizarproximosdoisanos.jpg"},'
 +' {"card":"Se fosses um animal que animal gostavas de ser ? Porquê?","url":"images/sefossesanimal.jpg"},'
 +' {"card":"Se fosses um jornalista, quem gostarias de entrevistar? Porquê ?","url":"images/sefossesjornalista.jpg"},'
 +' {"card":"Se fosses um objeto deste lugar, qual serias? Porquê ?","url":"images/sefossesobjeto.jpg"},'
 +' {"card":"Se fosses uma planta, qual serias? Porquê ?","url":"images/sefossesplanta.jpg"},'
 +' {"card":"Conta uma situação marcante que viveste com uma pessoa deste grupo.","url":"images/situacaomarcante.jpg"},'
 +' {"card":"Tens a tua sobrevivência garantida. Em que te ocupas?","url":"images/sobrevivenciagarantida.jpg"},'
 +' {"card":"Quais são os teus três maiores valores ?","url":"images/tresmaioresvalores.jpg"},'
 +' {"card": "Alguma vez viste a tua vida andar pra trás?","url":"images/vidaandarparatras.jpg"},'
 +' {"card": "Partilha um momento em que sentiste raiva. Como agiste?","url":"images/momentoraiva.jpg"},'
 +' {"card": "Se fosses um livro, que livro serias? Porquê?", "url":""}';